/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Provider;

import Business.Cdc;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProvidersEnterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Deepak
 */
public class HospitalAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Cdc system;
    private DB4OUtil db4o;

    public HospitalAdminWorkAreaJPanel(JPanel upc, UserAccount user, Organization org, Enterprise enterprise, Cdc system, DB4OUtil db4o) {
        initComponents();
        userProcessContainer = upc;
        userAccount = user;
        organization = org;
        this.enterprise = enterprise;
        this.system = system;
        this.db4o = db4o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        registerJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        createPatientJButton = new javax.swing.JButton();
        createClinicJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleJLabel.setText("Hospital Admin WorkArea");
        add(titleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        registerJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        registerJButton.setText("Apply for Registration");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });
        add(registerJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 230, -1));

        logoutJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 113, -1));

        createPatientJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createPatientJButton.setText("Create & Manage Patient");
        createPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientJButtonActionPerformed(evt);
            }
        });
        add(createPatientJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 231, -1));

        createClinicJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createClinicJButton.setText("Create & Manage Clinic");
        createClinicJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createClinicJButtonActionPerformed(evt);
            }
        });
        add(createClinicJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        ProvidersEnterprise pEnterprise = (ProvidersEnterprise) enterprise;

        RegistrationHospitalJPanel register = new RegistrationHospitalJPanel(userProcessContainer, userAccount, organization, pEnterprise, system);
        userProcessContainer.add("RegistrationHospitalJPanel", register);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_registerJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed

        db4o.storeSystem(system);
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void createPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientJButtonActionPerformed
        ManagePatientCatalogJPanel managePatientCatalogJPanel = new ManagePatientCatalogJPanel(userProcessContainer, system, userAccount, organization, enterprise);
        userProcessContainer.add("managePatientCatalogJPanel", managePatientCatalogJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createPatientJButtonActionPerformed

    private void createClinicJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createClinicJButtonActionPerformed
        ManageClinicCatalogJPanel manageClinicCatalogJPanel = new ManageClinicCatalogJPanel(userProcessContainer, userAccount, organization, enterprise);
        userProcessContainer.add("ManageClinicCatalogJPanel", manageClinicCatalogJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createClinicJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createClinicJButton;
    private javax.swing.JButton createPatientJButton;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton registerJButton;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
