/*
 * ManageHospitalCatalogJPanel.java
 *
 * Created on September 24, 2008, 2:40 PM
 */
package UserInterface.Provider;

import Business.Enterprise.ProvidersEnterprise;
import Business.Pharmacy.Pharmacy;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class ManagePharmacyCatalogJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ProvidersEnterprise providerEnterprise;

    /**
     * Creates new form ManageProductCatalogJPanel
     */
    public ManagePharmacyCatalogJPanel(JPanel upc, ProvidersEnterprise providerEnterprise) {
        initComponents();
        userProcessContainer = upc;
        this.providerEnterprise = providerEnterprise;
        refreshTable();
    }

    private void refreshTable() {
        int rowCount = pharmacyCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel) pharmacyCatalog.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Pharmacy p : providerEnterprise.getPharmacyDirectory().getPharmacyDirectory()) {
            Object row[] = new Object[3];
            row[0] = p;
            row[1] = p.getPharmacyID();
            row[2] = p.getPharmacyAddress();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pharmacyCatalog = new javax.swing.JTable();
        viewPButton = new javax.swing.JButton();
        createPButton = new javax.swing.JButton();
        searchPButton = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Pharmacy Catalog");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        pharmacyCatalog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pharmacyCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pharmacy Name", "Pharmacy ID", "Pharmacy Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pharmacyCatalog);
        if (pharmacyCatalog.getColumnModel().getColumnCount() > 0) {
            pharmacyCatalog.getColumnModel().getColumn(0).setResizable(false);
            pharmacyCatalog.getColumnModel().getColumn(1).setResizable(false);
            pharmacyCatalog.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 530, 89));

        viewPButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewPButton.setText("View Pharmacy Details ");
        viewPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPButtonActionPerformed(evt);
            }
        });
        add(viewPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 220, -1));

        createPButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createPButton.setText("Create New Pharmacy");
        createPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPButtonActionPerformed(evt);
            }
        });
        add(createPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 220, -1));

        searchPButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchPButton.setText("Search ");
        searchPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPButtonActionPerformed(evt);
            }
        });
        add(searchPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 180, 130, -1));

        backButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        add(backButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 110, -1));

        refreshButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refreshButton.setMargin(new java.awt.Insets(2, 1, 2, 1));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 80, -1));

        delButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delButton.setText("Delete Pharmacy(s)");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });
        add(delButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 190, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void viewPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPButtonActionPerformed
        // TODO add your handling code here:
        int row = pharmacyCatalog.getSelectedRow();
        int selectedRowCount = pharmacyCatalog.getSelectedRowCount();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a pharmacy to view the details");
            return;
        }
        if (selectedRowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one pharmacy");
        }
        Pharmacy p = (Pharmacy) pharmacyCatalog.getValueAt(row, 0);
        ViewPharmacyDetailJPanel vpdjp = new ViewPharmacyDetailJPanel(userProcessContainer, p);
        userProcessContainer.add("ViewHospitalDetailJPanel", vpdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPButtonActionPerformed

    private void createPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPButtonActionPerformed

        JTextField pharmacyNameTextField = new JTextField();
        JTextArea pharmacyAddressTextArea = new JTextArea();

        Object[] addPharmacy = {"Pharmacy Name:", pharmacyNameTextField, "Pharmacy Address:", pharmacyAddressTextArea};
        int option = JOptionPane.showConfirmDialog(null, addPharmacy, "Add Pharmacy", JOptionPane.OK_CANCEL_OPTION, -1);

        if (option == JOptionPane.YES_OPTION) {
            Pharmacy pharmacy = providerEnterprise.getPharmacyDirectory().addPharmacy();
            if (pharmacyNameTextField.getText() == null || pharmacyAddressTextArea.getText() == null) {
                JOptionPane.showMessageDialog(null, "Please provide a valid entry");
                return;

            }
            try {
                String name = pharmacyNameTextField.getText();
                String address = pharmacyAddressTextArea.getText();
                pharmacy.setPharmacyName(name);
                pharmacy.setPharmacyAddress(address);
                pharmacy.setAdmin("Unassigned");
                pharmacy.setFinanaceUser("Unassigned");
                pharmacy.setInventoryUser("Unassigned");
                pharmacy.setOrderUser("Unassigned");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide a valid entry");
                return;
            }
            JOptionPane.showMessageDialog(null, "Pharmacy details added successfully");
            refreshTable();
        }

    }//GEN-LAST:event_createPButtonActionPerformed

    private void searchPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPButtonActionPerformed
        // TODO add your handling code here:

        SearchForPharmacyJPanel sfpjp = new SearchForPharmacyJPanel(userProcessContainer, providerEnterprise);
        userProcessContainer.add("SearchForPharmacyJPanel", sfpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_searchPButtonActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton4ActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refreshTable();
}//GEN-LAST:event_refreshButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        int row = pharmacyCatalog.getSelectedRow();
        int selectedRowCount = pharmacyCatalog.getSelectedRowCount();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a pharmacy");
            return;
        }
        if (selectedRowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one pharmacy");
        }
        Pharmacy p = (Pharmacy) pharmacyCatalog.getValueAt(row, 0);
        providerEnterprise.getPharmacyDirectory().removePharmacy(p);
        refreshTable();
        JOptionPane.showMessageDialog(null, "Pharmacy deleted successfully");
    }//GEN-LAST:event_delButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton4;
    private javax.swing.JButton createPButton;
    private javax.swing.JButton delButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pharmacyCatalog;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchPButton;
    private javax.swing.JButton viewPButton;
    // End of variables declaration//GEN-END:variables
}
