/*
 * ManageHospitalCatalogJPanel.java
 *
 * Created on September 24, 2008, 2:40 PM
 */
package UserInterface.Provider;

import Business.Enterprise.ProvidersEnterprise;
import Business.Hospital.Hospital;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class ManageHospitalCatalogJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    ProvidersEnterprise providerEnterprise;

    /**
     * Creates new form ManageProductCatalogJPanel
     */
    public ManageHospitalCatalogJPanel(JPanel upc, ProvidersEnterprise providerEnterprise) {
        initComponents();
        userProcessContainer = upc;
        this.providerEnterprise = providerEnterprise;
        refreshTable();
    }

    private void refreshTable() {
        int rowCount = hospitalCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel) hospitalCatalog.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (Hospital h : providerEnterprise.getHospitalDirectory().getHospitalList()) {
            Object row[] = new Object[3];
            row[0] = h;
            row[1] = h.getHospitalID();
            row[2] = h.getHospitalAddress();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hospitalCatalog = new javax.swing.JTable();
        viewPButton = new javax.swing.JButton();
        createPButton = new javax.swing.JButton();
        searchPButton = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manage Hospital Catalog");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        hospitalCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Hospital ID", "Hospital Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(hospitalCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 530, 89));

        viewPButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewPButton.setText("View Hospital Details ");
        viewPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPButtonActionPerformed(evt);
            }
        });
        add(viewPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 220, -1));

        createPButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createPButton.setText("Create New Hospital");
        createPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPButtonActionPerformed(evt);
            }
        });
        add(createPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 220, -1));

        searchPButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchPButton.setText("Search ");
        searchPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPButtonActionPerformed(evt);
            }
        });
        add(searchPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 200, 130, -1));

        backButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        add(backButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 110, -1));

        refreshButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refreshButton.setMargin(new java.awt.Insets(2, 1, 2, 1));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 80, -1));

        delButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delButton.setText("Delete Hospital(s)");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });
        add(delButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 190, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void viewPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPButtonActionPerformed
        // TODO add your handling code here:
        int row = hospitalCatalog.getSelectedRow();
        int selectedRowCount = hospitalCatalog.getSelectedRowCount();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a hospital to view the details");
            return;
        }
        if (selectedRowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one hospital");
        }
        Hospital h = (Hospital) hospitalCatalog.getValueAt(row, 0);
        ViewHospitalDetailJPanel vpdjp = new ViewHospitalDetailJPanel(userProcessContainer, h);
        userProcessContainer.add("ViewHospitalDetailJPanel", vpdjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPButtonActionPerformed

    private void createPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPButtonActionPerformed

        JTextField hospitalNameTextField = new JTextField();
        JTextArea hospitalAddressTextArea = new JTextArea();

        Object[] addHospital = {"Hospital Name:", hospitalNameTextField, "Hospital Address:", hospitalAddressTextArea};
        int option = JOptionPane.showConfirmDialog(null, addHospital, "Add Hospital", JOptionPane.OK_CANCEL_OPTION, -1);

        if (option == JOptionPane.YES_OPTION) {
            Hospital hospital = providerEnterprise.getHospitalDirectory().addHospital();
            if (hospitalNameTextField.getText() == null || hospitalAddressTextArea.getText() == null) {
                JOptionPane.showMessageDialog(null, "Please provide a valid entry");
                return;

            }
            try {
                String name = hospitalNameTextField.getText();
                String address = hospitalAddressTextArea.getText();
                hospital.setHospitalName(name);
                hospital.setHospitalAddress(address);
                hospital.setAdmin("Unassigned");
                hospital.setFinanaceUser("Unassigned");
                hospital.setInventoryUser("Unassigned");
                hospital.setOrderUser("Unassigned");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please provide a valid entry");
                return;
            }
            JOptionPane.showMessageDialog(null, "Hospital details added successfully");
            refreshTable();
        }

    }//GEN-LAST:event_createPButtonActionPerformed

    private void searchPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPButtonActionPerformed
        // TODO add your handling code here:

        SearchForHospitalJPanel sfpjp = new SearchForHospitalJPanel(userProcessContainer, providerEnterprise);
        userProcessContainer.add("SearchForHospitalJPanel", sfpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_searchPButtonActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton4ActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refreshTable();
}//GEN-LAST:event_refreshButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        int row = hospitalCatalog.getSelectedRow();
        int selectedRowCount = hospitalCatalog.getSelectedRowCount();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a hospital");
            return;
        }
        if (selectedRowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one hospital");
        }
        Hospital h = (Hospital) hospitalCatalog.getValueAt(row, 0);
        providerEnterprise.getHospitalDirectory().removeHospital(h);
        refreshTable();
        JOptionPane.showMessageDialog(null, "Hospital deleted successfully");
    }//GEN-LAST:event_delButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton4;
    private javax.swing.JButton createPButton;
    private javax.swing.JButton delButton;
    private javax.swing.JTable hospitalCatalog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchPButton;
    private javax.swing.JButton viewPButton;
    // End of variables declaration//GEN-END:variables
}
