/*
 * ProviderAdminWorkAreaJPanel.java
 *
 * Created on October 10, 2008, 8:50 AM
 */
package UserInterface.Provider;

import Business.Cdc;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Enterprise.ProvidersEnterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Deepak
 */
public class ProviderAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    Cdc system;
    DB4OUtil db4o;
    UserAccount userAccount;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public ProviderAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, Cdc system, DB4OUtil db4o) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.db4o = db4o;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageHospitalEmployeeJButton = new javax.swing.JButton();
        registerHospitalJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        managePharmacylEmployeeJButton = new javax.swing.JButton();
        userPharmacyJButton = new javax.swing.JButton();
        registerPharmacyJButton = new javax.swing.JButton();
        reportJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Provider Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        userJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userJButton.setText("Manage Hospital User Account");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 231, -1));

        manageHospitalEmployeeJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        manageHospitalEmployeeJButton.setText("Manage Hospital Employee");
        manageHospitalEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHospitalEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageHospitalEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 231, -1));

        registerHospitalJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        registerHospitalJButton.setText("Create & Manage Hospital");
        registerHospitalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerHospitalJButtonActionPerformed(evt);
            }
        });
        add(registerHospitalJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 231, -1));

        logoutJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 113, -1));

        managePharmacylEmployeeJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        managePharmacylEmployeeJButton.setText("Manage Pharmacy Employee");
        managePharmacylEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePharmacylEmployeeJButtonActionPerformed(evt);
            }
        });
        add(managePharmacylEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 231, -1));

        userPharmacyJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userPharmacyJButton.setText("Manage Pharmacy User Account");
        userPharmacyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPharmacyJButtonActionPerformed(evt);
            }
        });
        add(userPharmacyJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        registerPharmacyJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        registerPharmacyJButton.setText("Create & Manage Pharmacy");
        registerPharmacyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPharmacyJButtonActionPerformed(evt);
            }
        });
        add(registerPharmacyJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 231, -1));

        reportJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reportJButton.setText("Report Vaccines");
        reportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportJButtonActionPerformed(evt);
            }
        });
        add(reportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ProvidersEnterprise providerEnterprise = (ProvidersEnterprise) enterprise;
        ManageHospitalUserAccountJPanel muajp = new ManageHospitalUserAccountJPanel(userProcessContainer, providerEnterprise, system);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageHospitalEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHospitalEmployeeJButtonActionPerformed
        ProvidersEnterprise providerEnterprise = (ProvidersEnterprise) enterprise;
        ManageHospitalEmployeeJPanel manageEmployeeJPanel = new ManageHospitalEmployeeJPanel(userProcessContainer, providerEnterprise.getOrganizationList(), providerEnterprise);
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageHospitalEmployeeJButtonActionPerformed

    private void registerHospitalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerHospitalJButtonActionPerformed
        ProvidersEnterprise providerEnterprise = (ProvidersEnterprise) enterprise;
        ManageHospitalCatalogJPanel manageHospitalJPanel = new ManageHospitalCatalogJPanel(userProcessContainer, providerEnterprise);
        userProcessContainer.add("ManageHospitalCatalogJPanel", manageHospitalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_registerHospitalJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        db4o.storeSystem(system);
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void managePharmacylEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePharmacylEmployeeJButtonActionPerformed
        ProvidersEnterprise providerEnterprise = (ProvidersEnterprise) enterprise;
        ManagePharmacyEmployeeJPanel manageEmployeeJPanel = new ManagePharmacyEmployeeJPanel(userProcessContainer, providerEnterprise.getOrganizationList(), providerEnterprise);
        userProcessContainer.add("ManagePharmacyEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePharmacylEmployeeJButtonActionPerformed

    private void userPharmacyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPharmacyJButtonActionPerformed
        ProvidersEnterprise providerEnterprise = (ProvidersEnterprise) enterprise;
        ManagePharmacyUserAccountJPanel muajp = new ManagePharmacyUserAccountJPanel(userProcessContainer, providerEnterprise, system);
        userProcessContainer.add("ManagePharmacyUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userPharmacyJButtonActionPerformed

    private void registerPharmacyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPharmacyJButtonActionPerformed
        ProvidersEnterprise providerEnterprise = (ProvidersEnterprise) enterprise;
        ManagePharmacyCatalogJPanel manageHospitalJPanel = new ManagePharmacyCatalogJPanel(userProcessContainer, providerEnterprise);
        userProcessContainer.add("ManagePharmacyCatalogJPanel", manageHospitalJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_registerPharmacyJButtonActionPerformed

    private void reportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportJButtonActionPerformed

        ProvidersEnterprise providerEnterprise = (ProvidersEnterprise) enterprise;
        ReportVaccinesJPanel reportVaccinesJPanel = new ReportVaccinesJPanel(userProcessContainer, system, userAccount, enterprise);
        userProcessContainer.add("ReportVaccinesJPanel", reportVaccinesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_reportJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton manageHospitalEmployeeJButton;
    private javax.swing.JButton managePharmacylEmployeeJButton;
    private javax.swing.JButton registerHospitalJButton;
    private javax.swing.JButton registerPharmacyJButton;
    private javax.swing.JButton reportJButton;
    private javax.swing.JButton userJButton;
    private javax.swing.JButton userPharmacyJButton;
    // End of variables declaration//GEN-END:variables

}
