/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Provider;

import Business.Cdc;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.ProvidersEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Pharmacy.Pharmacy;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RegistrationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Deepak
 */
public class RegistrationPharmacyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationPharmacy
     */
    private JPanel upc;
    private UserAccount ua;
    private Organization org;
    private ProvidersEnterprise enterprise;
    private Cdc system;

    public RegistrationPharmacyJPanel(JPanel upc, UserAccount ua, Organization org, ProvidersEnterprise enterprise, Cdc system) {
        initComponents();
        this.upc = upc;
        this.ua = ua;
        this.org = org;
        this.enterprise = enterprise;
        this.system = system;
        pharmacyNameText.setText(ua.getEmployee().getPharmacy().getPharmacyName());
        populateTextBox();
    }

    private void populateTextBox() {
        for (WorkRequest request : ua.getWorkQueue().getWorkRequestList()) {
            RegistrationRequest req = (RegistrationRequest) request;
            enrollStatusText.setText(req.getRegistrationStatus() == null ? req.getStatus() : req.getRegistrationStatus());
            approverText1.setText(req.getReceiver() == null ? null : req.getReceiver().getEmployee().getFname());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameLabel = new javax.swing.JLabel();
        pharmacyNameText = new javax.swing.JTextField();
        lastnameLabel1 = new javax.swing.JLabel();
        enrollStatusText = new javax.swing.JTextField();
        enrollButton = new javax.swing.JButton();
        Approver = new javax.swing.JLabel();
        approverText1 = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        firstNameLabel.setText("Pharmacy Name");
        add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        pharmacyNameText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(pharmacyNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 160, -1, -1));

        lastnameLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lastnameLabel1.setText("Registration Status");
        add(lastnameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, -1, -1));

        enrollStatusText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(enrollStatusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 130, -1));

        enrollButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enrollButton.setText("Register");
        enrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollButtonActionPerformed(evt);
            }
        });
        add(enrollButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        Approver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Approver.setText("Approver");
        add(Approver, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        approverText1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(approverText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, -1, -1));

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Pharmacy Order History Page");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void enrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollButtonActionPerformed
        // TODO add your handling code here:
        RegistrationRequest request = new RegistrationRequest();
        for (WorkRequest request1 : ua.getWorkQueue().getWorkRequestList()) {
            if (request1.getStatus().equals("Approved")) {
                JOptionPane.showMessageDialog(null, "You've already enrolled");
                return;
            } else if (request1.getStatus().equals("Processing") || request1.getStatus().contains("Pending")) {
                JOptionPane.showMessageDialog(null, "A request is already under process");
                return;
            }
        }
        request.setSender(ua);
        request.setStatus("Processing");
        request.setRequestType("Pharmacy Registration Request");
        for (Pharmacy p : enterprise.getPharmacyDirectory().getPharmacyDirectory()) {
            if (ua.getEmployee().getPharmacy().getPharmacyName().equals(p.getPharmacyName())) {
                request.setRegistrationProcessId(p.getPharmacyID());
            }
        }
        JOptionPane.showMessageDialog(null, "Request has been submitted for approval");
        enrollStatusText.setText(request.getStatus());
        approverText1.setText("");
        PHDEnterprise e1 = null;

        Network n = null;
        for (Network network : system.getNetworkDirectory().getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e == enterprise) {
                    n = network;
                    break;
                }
            }
        }

        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof PHDEnterprise) {
                e1 = (PHDEnterprise) e;
                break;
            }
        }
        if (e1 != null) {
            e1.getWorkQueue().getWorkRequestList().add(request);
            ua.getWorkQueue().getWorkRequestList().add(request);
        }

    }//GEN-LAST:event_enrollButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Approver;
    private javax.swing.JTextField approverText1;
    private javax.swing.JButton backButton;
    private javax.swing.JButton enrollButton;
    private javax.swing.JTextField enrollStatusText;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastnameLabel1;
    private javax.swing.JTextField pharmacyNameText;
    // End of variables declaration//GEN-END:variables
}
