/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Provider;

import Business.Cdc;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.Vaccine.Vaccine;
import Business.WorkQueue.ReportVaccineWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class ReportVaccinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportVaccinesJPanel
     */
    private JPanel upc;
    private Cdc system;
    private UserAccount userAccount;
    private Enterprise enterprise;

    public ReportVaccinesJPanel(JPanel upc, Cdc system, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.upc = upc;
        this.system = system;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        populateCombo();
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) reportVaccinesJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest r : userAccount.getWorkQueue().getWorkRequestList()) {
            if (r.getRequestType().equals("Report")) {
                ReportVaccineWorkRequest rv = (ReportVaccineWorkRequest) r;
                Object row[] = new Object[3];
                row[0] = rv.getVaccine();
                row[1] = rv.getVaccine().getVaccineName();
                row[2] = rv.getStatus();
                model.addRow(row);
            }
        }
    }

    public void populateCombo() {
        vaccineNameJComboBox.removeAllItems();
        for (Vaccine v : system.getVaccineCatalog().getVaccineCatalog()) {
            vaccineNameJComboBox.addItem(v.getVaccineName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vaccineNameJComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportJTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageJTextArea = new javax.swing.JTextArea();
        sendReportJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reportVaccinesJTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vaccineNameJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(vaccineNameJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 140, -1));

        reportJTextArea.setColumns(20);
        reportJTextArea.setRows(5);
        jScrollPane2.setViewportView(reportJTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 295, 80));

        messageJTextArea.setColumns(20);
        messageJTextArea.setRows(5);
        jScrollPane3.setViewportView(messageJTextArea);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 295, 80));

        sendReportJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sendReportJButton.setText("Send Report");
        sendReportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendReportJButtonActionPerformed(evt);
            }
        });
        add(sendReportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 123, -1));

        reportVaccinesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine ID", "Vaccine Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportVaccinesJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 850, 185));

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Report Vacccines");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sendReportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendReportJButtonActionPerformed
        // TODO add your handling code here:
        Vaccine vaccine = null;
        String vaccineName = (String) vaccineNameJComboBox.getSelectedItem();
        for (Vaccine v : system.getVaccineCatalog().getVaccineCatalog()) {
            if (v.getVaccineName().equals(vaccineName)) {
                vaccine = v;
            }
        }
        if (vaccine == null) {
            JOptionPane.showMessageDialog(null, "The vaccine is not present");
            return;
        }
        String report = reportJTextArea.getText();
        String message = messageJTextArea.getText();

        if (report.isEmpty() || message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please provide inputs for all fields");
            return;
        }

        ReportVaccineWorkRequest request = new ReportVaccineWorkRequest();
        WorkRequest r = request;
        request.setVaccine(vaccine);
        request.setMessage(message);
        request.setIssueReport(report);
        request.setSender(userAccount);
        request.setStatus("Reported to PHD");
        request.setRequestType("Report");

        Network n = null;
        Enterprise e1 = null;
        for (Network network : system.getNetworkDirectory().getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e == enterprise) {
                    n = network;
                    break;
                }
            }
        }
        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof PHDEnterprise) {
                e1 = e;
            }
        }
        if (e1 != null) {
            e1.getWorkQueue().getWorkRequestList().add(r);
            userAccount.getWorkQueue().getWorkRequestList().add(r);
        }
        JOptionPane.showMessageDialog(null, "Report sent to PHD");
        populateTable();
    }//GEN-LAST:event_sendReportJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messageJTextArea;
    private javax.swing.JTextArea reportJTextArea;
    private javax.swing.JTable reportVaccinesJTable;
    private javax.swing.JButton sendReportJButton;
    private javax.swing.JComboBox vaccineNameJComboBox;
    // End of variables declaration//GEN-END:variables
}
