/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NationalDistributorRole;

import Business.Cdc;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Deepak
 */
public class NationalDistributorAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NationalDistributorAdminWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Cdc system;
    private DB4OUtil db4o;

    public NationalDistributorAdminWorkAreaJPanel(JPanel userProcessContainer,
            UserAccount userAccount, Enterprise enterprise,
            Cdc system, DB4OUtil db4o) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.system = system;
        this.db4o = db4o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        approveOrdersJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();
        titleJLabel = new javax.swing.JLabel();
        paymentJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        approveOrdersJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        approveOrdersJButton.setText("Approve Orders");
        approveOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveOrdersJButtonActionPerformed(evt);
            }
        });
        add(approveOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 260, 187, -1));

        logoutJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });
        add(logoutJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 113, -1));

        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleJLabel.setText("National Distributor Work Area");
        add(titleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        paymentJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        paymentJButton.setText("Payment");
        paymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentJButtonActionPerformed(evt);
            }
        });
        add(paymentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void approveOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveOrdersJButtonActionPerformed
        ApproveCdcOrdersJPanel approve = new ApproveCdcOrdersJPanel(userProcessContainer, userAccount, enterprise, system);
        userProcessContainer.add("ApproveCdcOrdersJPanel", approve);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_approveOrdersJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed

        db4o.storeSystem(system);
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void paymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentJButtonActionPerformed
        OrderPaymentJPanel approve = new OrderPaymentJPanel(userProcessContainer, userAccount, enterprise, system);
        userProcessContainer.add("OrderPaymentJPanel", approve);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_paymentJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveOrdersJButton;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton paymentJButton;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
