/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NationalDistributorRole;

import Business.Cdc;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FinanceRequest;
import Business.WorkQueue.ManufactureFinanceRequest;
import Business.WorkQueue.WorkRequest;
import com.sun.org.apache.xml.internal.serialize.LineSeparator;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Deepak
 */
public class OrderPaymentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderPaymentJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Cdc system;

    public OrderPaymentJPanel(JPanel upc, UserAccount user,
            Enterprise enterprise, Cdc system) {
        initComponents();
        userProcessContainer = upc;
        userAccount = user;
        this.enterprise = enterprise;
        this.system = system;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) orderJTable.getModel();
        dtm.setRowCount(0);
        for (WorkRequest request : system.getNationalDistributor().getWorkQueue().getWorkRequestList()) {
            if (request instanceof ManufactureFinanceRequest) {
                ManufactureFinanceRequest req = (ManufactureFinanceRequest) request;
                Object[] row = new Object[4];
                row[0] = req.getOrderId();
                row[1] = req.getPrice();
                row[2] = req.getSender();
                row[3] = req;
                dtm.addRow(row);
            }
        }
    }

    public void toExcel(JTable table, File file) {
        try {
            TableModel model = table.getModel();
            FileWriter excel = new FileWriter(file);

            for (int i = 0; i < model.getColumnCount(); i++) {
                excel.write(model.getColumnName(i) + ",");
            }

            excel.write("\n");

            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    excel.write(model.getValueAt(i, j).toString() + ",");
                }
                excel.write("\n");
            }

            excel.close();

        } catch (IOException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        vaccineCatalogJTable = new javax.swing.JTable();
        orderDetailsJButton = new javax.swing.JButton();
        approvePaymentJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exportJButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Total Price", "Sender", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderJTable);
        if (orderJTable.getColumnModel().getColumnCount() > 0) {
            orderJTable.getColumnModel().getColumn(0).setResizable(false);
            orderJTable.getColumnModel().getColumn(1).setResizable(false);
            orderJTable.getColumnModel().getColumn(2).setResizable(false);
            orderJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 477, 89));

        vaccineCatalogJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "ID", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(vaccineCatalogJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 375, 92));

        orderDetailsJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        orderDetailsJButton.setText("View Order Details");
        orderDetailsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDetailsJButtonActionPerformed(evt);
            }
        });
        add(orderDetailsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        approvePaymentJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        approvePaymentJButton.setText("Pay");
        approvePaymentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvePaymentJButtonActionPerformed(evt);
            }
        });
        add(approvePaymentJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, -1, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Payment Page");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        exportJButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        exportJButton.setText("Export To Excel");
        exportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportJButtonActionPerformed(evt);
            }
        });
        add(exportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void orderDetailsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDetailsJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = orderJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select an order to view");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) vaccineCatalogJTable.getModel();
        dtm.setRowCount(0);
        ManufactureFinanceRequest request = (ManufactureFinanceRequest) orderJTable.getValueAt(selectedRow, 3);

        Object[] row = new Object[3];
        row[0] = request.getVaccine().getVaccineName();
        row[1] = request.getVaccine().getID();
        row[2] = request.getQuantity();
        dtm.addRow(row);
    }//GEN-LAST:event_orderDetailsJButtonActionPerformed

    private void approvePaymentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvePaymentJButtonActionPerformed
        int selectedRow = orderJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a order to approve");
            return;
        }
        ManufactureFinanceRequest financeRequest = (ManufactureFinanceRequest) orderJTable.getValueAt(selectedRow, 3);
        if (financeRequest.getStatus().equals("Approved") || financeRequest.getStatus().equals("Rejected")) {
            JOptionPane.showMessageDialog(null, "Order Request already processed");
            return;
        }
        financeRequest.setReceiver(userAccount);
        financeRequest.setStatus("Paid");
        populateTable();
    }//GEN-LAST:event_approvePaymentJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void exportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportJButtonActionPerformed
        toExcel(orderJTable, new File("C:\\distributorBill.csv"));
    }//GEN-LAST:event_exportJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approvePaymentJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton exportJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton orderDetailsJButton;
    private javax.swing.JTable orderJTable;
    private javax.swing.JTable vaccineCatalogJTable;
    // End of variables declaration//GEN-END:variables
}
