/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PublicHealthDept;

import Business.Cdc;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHDEnterprise;
import Business.Enterprise.ProvidersEnterprise;
import Business.Hospital.Hospital;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RegistrationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class ApproveHospitalsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Organization organization;
    private Enterprise enterprise;
    private Cdc system;

    /**
     * Creates new form ApproveHospitalsJPanel
     */
    public ApproveHospitalsJPanel(JPanel userProcessContainer,
            UserAccount userAccount, Organization organization,
            Enterprise enterprise, Cdc system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.system = system;
        populateTable();

    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) hospitalsTable.getModel();
        dtm.setRowCount(0);
        for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {

            if (request.getRequestType().equals("Hospital Registration Request")) {
                RegistrationRequest req = (RegistrationRequest) request;
                Object[] row = new Object[4];
                row[0] = req.getRegistrationProcessId();
                row[1] = request.getSender().getEmployee().getHospital().getHospitalName();
                row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getFname();
                row[3] = request;
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hospitalsTable = new javax.swing.JTable();
        assignToMeButton = new javax.swing.JButton();
        approveHospital = new javax.swing.JButton();
        rejectHospital = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospitalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital ID", "Hospital Name", "Approver Name", "Registration Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(hospitalsTable);
        if (hospitalsTable.getColumnModel().getColumnCount() > 0) {
            hospitalsTable.getColumnModel().getColumn(0).setResizable(false);
            hospitalsTable.getColumnModel().getColumn(1).setResizable(false);
            hospitalsTable.getColumnModel().getColumn(2).setResizable(false);
            hospitalsTable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 505, 88));

        assignToMeButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        assignToMeButton.setText("Assign To Me");
        assignToMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeButtonActionPerformed(evt);
            }
        });
        add(assignToMeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        approveHospital.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        approveHospital.setText("Approve Hospital");
        approveHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveHospitalActionPerformed(evt);
            }
        });
        add(approveHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        rejectHospital.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rejectHospital.setText("Reject Hospital");
        rejectHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectHospitalActionPerformed(evt);
            }
        });
        add(rejectHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Approve Hospitals Page");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignToMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = hospitalsTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        PHDEnterprise phd = (PHDEnterprise) enterprise;
        for (Hospital hospital : phd.getProvidersEnterprise().getHospitalDirectory().getHospitalList()) {
            JOptionPane.showMessageDialog(null, hospital.getHospitalName());
        }
        RegistrationRequest request = (RegistrationRequest) hospitalsTable.getValueAt(selectedRow, 3);
        if (hospitalsTable.getValueAt(selectedRow, 2) == null) {
            request.setReceiver(userAccount);
            request.setStatus("Pending for approval");
            request.setRegistrationStatus("Pending for Approval");
            populateTable();
        } else {
            JOptionPane.showMessageDialog(null, "Request has been assigned already");
        }
    }//GEN-LAST:event_assignToMeButtonActionPerformed

    private void approveHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveHospitalActionPerformed
        // TODO add your handling code here:
        int selectedRow = hospitalsTable.getSelectedRow();
        RegistrationRequest request = (RegistrationRequest) hospitalsTable.getValueAt(selectedRow, 3);
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a order to approve");
            return;
        }
        if (request.getStatus().equals("Approved") || request.getStatus().equals("Rejected")) {
            JOptionPane.showMessageDialog(null, "Registration Request already processed");
            return;
        }
        if (request.getReceiver() == null) {
            JOptionPane.showMessageDialog(null, "Request has to be assigned first");
            return;
        }
        if (!(request.getReceiver() == userAccount)) {
            JOptionPane.showMessageDialog(null, "Request has been assigned to another sales rep");
            return;
        }
        request.setStatus("Approved");
        request.setRegistrationStatus("Approved");
        ProvidersEnterprise p = null;
        Network n = null;
        for (Network network : system.getNetworkDirectory().getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (e == enterprise) {
                    n = network;
                    break;
                }
            }
        }

        for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof ProvidersEnterprise) {
                p = (ProvidersEnterprise) e;
                break;
            }
        }

        if (p != null) {
            for (Hospital h : p.getHospitalDirectory().getHospitalList()) {
                if (h.getHospitalName().equals(request.getSender().getEmployee().getHospital().getHospitalName())) {
                    h.setRegistrationStatus("Approved");
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Request processed");
        populateTable();
    }//GEN-LAST:event_approveHospitalActionPerformed

    private void rejectHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectHospitalActionPerformed
        // TODO add your handling code here:
        int selectedRow = hospitalsTable.getSelectedRow();
        RegistrationRequest request = (RegistrationRequest) hospitalsTable.getValueAt(selectedRow, 3);
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a order to approve");
            return;
        }
        if (request.getStatus().equals("Approved") || request.getStatus().equals("Rejected")) {
            JOptionPane.showMessageDialog(null, "Enrollment Request already processed");
            return;
        }
        if (request.getReceiver() == null) {
            JOptionPane.showMessageDialog(null, "Request has to be assigned first");
            return;
        }
        if (!(request.getReceiver() == userAccount)) {
            JOptionPane.showMessageDialog(null, "Request has been assigned to another sales rep");
            return;
        }
        request.setRegistrationStatus("Rejected");
        request.setStatus("Rejected");
        JOptionPane.showMessageDialog(null, "Request processed");
        populateTable();
    }//GEN-LAST:event_rejectHospitalActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveHospital;
    private javax.swing.JButton assignToMeButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTable hospitalsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rejectHospital;
    // End of variables declaration//GEN-END:variables
}
