/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PublicHealthDept;

import Business.Cdc;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ReportVaccineWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class ReportVaccinesToCDCJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportVaccinesToCDCJPanel
     */
    private JPanel upc;
    private Cdc system;
    private Enterprise enterprise;
    private UserAccount userAccount;

    public ReportVaccinesToCDCJPanel(JPanel upc, Cdc system, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.upc = upc;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.system = system;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) reportJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : enterprise.getWorkQueue().getWorkRequestList()) {
            if (request.getRequestType().equals("Report")) {
                ReportVaccineWorkRequest report = (ReportVaccineWorkRequest) request;
                Object row[] = new Object[3];
                row[0] = report.getVaccine().getID();
                row[1] = report;
                row[2] = report.getStatus();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reportJTable = new javax.swing.JTable();
        refreshJButton = new javax.swing.JButton();
        viewJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vaccineNameJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportJTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        messageJTextArea = new javax.swing.JTextArea();
        forwardJButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reportJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine ID", "Vaccine Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reportJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 610, 100));

        refreshJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        refreshJButton.setText("Refresh Table");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        viewJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewJButton.setText("View Report");
        viewJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJButtonActionPerformed(evt);
            }
        });
        add(viewJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        jLabel2.setText("Vaccine Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, 20));

        jLabel3.setText("Issue Report");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        jLabel4.setText("Message");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));
        add(vaccineNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 140, -1));

        reportJTextArea.setColumns(20);
        reportJTextArea.setRows(5);
        jScrollPane2.setViewportView(reportJTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 240, 80));

        messageJTextArea.setColumns(20);
        messageJTextArea.setRows(5);
        jScrollPane3.setViewportView(messageJTextArea);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 240, 80));

        forwardJButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        forwardJButton.setText("Forward to CDC");
        forwardJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardJButtonActionPerformed(evt);
            }
        });
        add(forwardJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, -1, -1));

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Report Vaccines");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void viewJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = reportJTable.getSelectedRow();
        int rowC = reportJTable.getSelectedRowCount();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a report");
            return;
        }

        if (rowC > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one report");
            return;
        }

        ReportVaccineWorkRequest report = (ReportVaccineWorkRequest) reportJTable.getValueAt(selectedRow, 1);
        vaccineNameJTextField.setText(report.getVaccine().getVaccineName());
        messageJTextArea.setText(report.getMessage());
        reportJTextArea.setText(report.getIssueReport());

        populateTable();
    }//GEN-LAST:event_viewJButtonActionPerformed

    private void forwardJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = reportJTable.getSelectedRow();
        int rowC = reportJTable.getSelectedRowCount();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a report");
            return;
        }

        if (rowC > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one report");
            return;
        }
        ReportVaccineWorkRequest report = (ReportVaccineWorkRequest) reportJTable.getValueAt(selectedRow, 1);
        WorkRequest request = report;
        request.setStatus("Sent to CDC");
        system.getWorkQueue().getWorkRequestList().add(request);
        JOptionPane.showMessageDialog(null, "Report forwarded to CDC");
        populateTable();
    }//GEN-LAST:event_forwardJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton forwardJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea messageJTextArea;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JTable reportJTable;
    private javax.swing.JTextArea reportJTextArea;
    private javax.swing.JTextField vaccineNameJTextField;
    private javax.swing.JButton viewJButton;
    // End of variables declaration//GEN-END:variables
}
