/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Manufacturer;

import Business.Cdc;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ReportVaccineWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class ViewReportsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewReportsJPanel
     */
    private JPanel upc;
    private Enterprise enterprise;
    private Cdc system;
    private UserAccount userAccount;

    public ViewReportsJPanel(JPanel upc, Enterprise enterprise, Cdc system, UserAccount userAccount) {
        initComponents();
        this.upc = upc;
        this.enterprise = enterprise;
        this.system = system;
        this.userAccount = userAccount;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) complaintsJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : system.getWorkQueue().getWorkRequestList()) {
            if (request.getRequestType().equalsIgnoreCase("Report")) {
                ReportVaccineWorkRequest report = (ReportVaccineWorkRequest) request;
                if (report.getVaccine().getManufacturer().equals(userAccount.getEmployee().getFname())) {
                    Object row[] = new Object[6];
                    row[0] = report;
                    row[1] = report.getVaccine().getVaccineName();
                    row[2] = report.getMessage();
                    row[3] = report.getSender().getEmployee().getFname();
                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        complaintsJTable = new javax.swing.JTable();
        readReportJButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complaintsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine ID", "Vaccine Name", "Message", "Sender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(complaintsJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 723, 162));

        readReportJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        readReportJButton.setText("Read Issue Report");
        readReportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readReportJButtonActionPerformed(evt);
            }
        });
        add(readReportJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, -1, -1));

        backButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("View Vaccine Reports");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void readReportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readReportJButtonActionPerformed
        // TODO add your handling code here:
        JTextField vaccineName = new JTextField();
        JTextField sender = new JTextField();
        JTextArea issue = new JTextArea();

        int row = complaintsJTable.getSelectedRow();
        int rowC = complaintsJTable.getSelectedRowCount();
        if (row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a complaint to view the issue report");
            return;
        }
        if (rowC > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one complaint");
            return;
        }

        ReportVaccineWorkRequest report = (ReportVaccineWorkRequest) complaintsJTable.getValueAt(row, 0);
        vaccineName.setText(report.getVaccine().getVaccineName());
        sender.setText(report.getSender().getEmployee().getFname());
        issue.setText(report.getIssueReport());

        Object[] viewIssue = {"Vaccine Name:", vaccineName, "Sender:", sender, "Issue Report:", issue};
        JOptionPane.showConfirmDialog(null, viewIssue, "Issue Report", JOptionPane.CLOSED_OPTION, -1);
    }//GEN-LAST:event_readReportJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable complaintsJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton readReportJButton;
    // End of variables declaration//GEN-END:variables
}
